[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/api/*"
  to = "https://birthday-backend-bnws.onrender.com/:splat"
  status = 200
  force = true


