services:
  - type: web
    name: birthday-backend
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python -c "from database import ensure_database_exists; ensure_database_exists()" && \
      gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: birthday-db
          property: connectionString
      # Uncomment and set these if you want to store Twilio creds in Render
      # - key: TWILIO_ACCOUNT_SID
      #   value: your-sid
      # - key: TWILIO_AUTH_TOKEN
      #   value: your-token
      # - key: TWILIO_WHATSAPP_NUMBER
      #   value: whatsapp:+14155238886

  - type: pserv
    name: birthday-db
    env: docker
    plan: free
    region: oregon
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

