services:
  - type: web
    name: birthday-backend
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # Uncomment and set these if you want to store Twilio creds in Render
      # - key: TWILIO_ACCOUNT_SID
      #   value: your-sid
      # - key: TWILIO_AUTH_TOKEN
      #   value: your-token
      # - key: TWILIO_WHATSAPP_NUMBER
      #   value: whatsapp:+14155238886

